#!/usr/bin/env Rscript
# pybnlearn: reference results for hill climbing, generated by R's bnlearn.
#
# Structure learning is where a port is easiest to get subtly wrong: a search
# that disagrees with R by one arc still returns a perfectly plausible network,
# and nothing about the output says it is wrong.  So the fixtures record the
# learned structure *and* the per-node scores, across several data sets, scores,
# hyperparameters and constraint sets.
#
# Usage: Rscript tools/gen_r_hc_fixtures.R [outdir]
#
# Copyright (C) 2026 the pybnlearn authors.
# Licensed under the GNU General Public License version 3 or later.

suppressMessages(library(bnlearn))

args = commandArgs(trailingOnly = TRUE)
outdir = if (length(args) > 0) args[1] else "tests/parity/fixtures"
dir.create(outdir, showWarnings = FALSE, recursive = TRUE)

num = function(x) sprintf("%.17g", as.numeric(x))
jstr = function(s) paste0('"', gsub('"', '\\\\"', s), '"')
jarr = function(v) if (length(v) == 0) "[]" else
                     paste0("[", paste(sapply(v, jstr), collapse = ","), "]")
jnums = function(v) paste0("[", paste(sapply(v, num), collapse = ","), "]")

# Arc sets are compared as sets, so they are emitted as "from>to" strings.
jarcs = function(a) if (nrow(a) == 0) "[]" else
                      jarr(paste(a[, "from"], a[, "to"], sep = ">"))

datasets = list()
for (nm in c("learning.test", "asia", "coronary", "lizards", "insurance",
             "alarm", "gaussian.test", "marks")) {
  e = new.env()
  data(list = nm, envir = e)
  d = get(nm, envir = e)
  datasets[[nm]] = d
  write.csv(d, file.path(outdir, paste0(nm, ".csv")),
            row.names = FALSE, quote = FALSE)
}

discrete.sets = c("learning.test", "asia", "coronary", "lizards",
                  "insurance", "alarm")
continuous.sets = c("gaussian.test", "marks")

records = character(0)

emit = function(dataset, score, extra, wl, bl, maxp, net, data) {
  # score(..., by.node = TRUE) is the public equivalent of the internal
  # per.node.score(), and applies the same argument defaults.
  scores = do.call(bnlearn::score,
             c(list(x = net, data = data, type = score, by.node = TRUE),
               extra))

  extra.json = if (length(extra) == 0) "{}" else
    paste0("{", paste(sprintf('%s:%s', sapply(names(extra), jstr),
                              sapply(extra, num)), collapse = ","), "}")

  sprintf(paste0('{"dataset":%s,"score":%s,"extra":%s,"whitelist":%s,',
                 '"blacklist":%s,"maxp":%s,"modelstring":%s,"arcs":%s,',
                 '"nodes":%s,"node.scores":%s}'),
    jstr(dataset), jstr(score), extra.json, jarcs(wl), jarcs(bl),
    if (is.infinite(maxp)) "null" else num(maxp),
    jstr(modelstring(net)), jarcs(net$arcs),
    jarr(names(net$nodes)), jnums(scores))
}

no.arcs = matrix(character(0), ncol = 2, dimnames = list(NULL, c("from", "to")))

run = function(dataset, score, extra = list(), wl = NULL, bl = NULL,
               maxp = Inf) {
  data = datasets[[dataset]]
  argv = c(list(x = data, score = score, maxp = maxp), extra)
  if (!is.null(wl)) argv$whitelist = wl
  if (!is.null(bl)) argv$blacklist = bl
  cat("  ", dataset, score, "\n", file = stderr())
  net = do.call(hc, argv)
  records <<- c(records,
    emit(dataset, score, extra,
         if (is.null(wl)) no.arcs else wl,
         if (is.null(bl)) no.arcs else bl,
         maxp, net, data))
}

# --- plain runs -------------------------------------------------------------
#
# The NML scores (fnml, qnml) build a regret table whose size grows with the
# number of parent configurations, so running them on the larger networks
# exhausts memory in R itself.  They are therefore exercised only on the small
# data sets, and the large ones stick to the scores people actually use on
# networks that size.

small.discrete = c("learning.test", "asia", "coronary", "lizards")
large.discrete = c("insurance", "alarm")

for (ds in small.discrete) {
  for (sc in c("bic", "aic", "loglik", "k2", "fnml", "qnml"))
    run(ds, sc)
  for (iss in c(1, 5, 20))
    run(ds, "bde", extra = list(iss = iss))
  run(ds, "bds", extra = list(iss = 1))
  run(ds, "bdj")
}

# The unpenalised scores (loglik, k2) let hill climbing keep adding parents on
# the larger networks until the conditional probability tables exhaust memory,
# in R as much as anywhere, so they are only run here under a parent limit.
for (ds in large.discrete) {
  for (sc in c("bic", "aic"))
    run(ds, sc)
  run(ds, "bde", extra = list(iss = 1))
  run(ds, "bde", extra = list(iss = 10))
  run(ds, "loglik", maxp = 3)
  run(ds, "k2", maxp = 3)
}

for (ds in continuous.sets) {
  for (sc in c("bic-g", "aic-g", "loglik-g"))
    run(ds, sc)
  run(ds, "bge", extra = list(iss.mu = 1))
}

# --- non-default hyperparameters -------------------------------------------

run("learning.test", "bic", extra = list(k = 1))
run("learning.test", "bic", extra = list(k = 5))
run("learning.test", "aic", extra = list(k = 3))
run("gaussian.test", "bic-g", extra = list(k = 2))

# --- constraints ------------------------------------------------------------

wl1 = data.frame(from = "A", to = "F", stringsAsFactors = FALSE)
bl1 = data.frame(from = c("A", "C"), to = c("B", "D"),
                 stringsAsFactors = FALSE)

run("learning.test", "bic", wl = wl1)
run("learning.test", "bic", bl = bl1)
run("learning.test", "bic", wl = wl1, bl = bl1)
run("learning.test", "bde", extra = list(iss = 1), bl = bl1)

for (mp in c(1, 2, 3))
  run("learning.test", "bic", maxp = mp)
for (mp in c(1, 2))
  run("asia", "bic", maxp = mp)
run("insurance", "bic", maxp = 3)

wl2 = data.frame(from = "A", to = "T", stringsAsFactors = FALSE)
bl2 = data.frame(from = "S", to = "L", stringsAsFactors = FALSE)
run("asia", "bic", wl = wl2, bl = bl2)
run("asia", "bde", extra = list(iss = 10), wl = wl2)

wl3 = data.frame(from = "A", to = "B", stringsAsFactors = FALSE)
run("gaussian.test", "bic-g", wl = wl3)
run("gaussian.test", "bic-g", maxp = 2)

out = file.path(outdir, "hc.json")
writeLines(paste0("[\n  ", paste(records, collapse = ",\n  "), "\n]"), out)

cat(sprintf("wrote %s: %d reference networks\n", out, length(records)))
cat(sprintf("R %s, bnlearn %s\n", getRversion(),
            as.character(packageVersion("bnlearn"))))
