#!/usr/bin/env python3
"""Regenerate src/c/meson.build.

Meson has no globbing, on purpose: an explicit file list is what makes a build
reproducible.  That is a poor fit for a vendored tree of ~270 files that gets
replaced wholesale on every upstream release, so the list is generated instead
of maintained.  Run this after dropping in a new bnlearn or R tarball.

Copyright (C) 2026 the pybnlearn authors.
Licensed under the GNU General Public License version 3 or later.
"""

import glob
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_C = os.path.join(os.path.dirname(HERE), "src", "c")

HEADER = """# Generated by tools/regen_meson_sources.py -- do not edit the file lists by
# hand; re-run that script after adding or updating vendored sources.
#
# The C core is built as three static libraries because each needs a different
# view of the world:
#
#   nmath   - R's own maths library, compiled against R's headers.  It is the
#             reference implementation, so it must NOT see the reimplemented
#             API in compat/, or it would call back into the shim.
#   linpack - R's Fortran QR routines.  Translating these to C is what removes
#             the Fortran toolchain from the wheel build.
#   bnlearn - the vendored bnlearn sources, byte-identical to upstream, plus
#             the compatibility layer, compiled against the shim R headers in
#             compat/rapi/.

compat_inc = include_directories('compat', 'compat/rapi')
nmath_inc = include_directories('nmath')
"""

FOOTER = """
nmath_lib = static_library(
  'pybn_nmath',
  nmath_sources,
  c_args: ['-DMATHLIB_STANDALONE'],
  include_directories: nmath_inc,
  dependencies: [m_dep],
  pic: true,
)

linpack_lib = static_library(
  'pybn_linpack',
  linpack_sources,
  pic: true,
)

bnlearn_lib = static_library(
  'pybn_bnlearn',
  bnlearn_sources,
  include_directories: compat_inc,
  dependencies: [m_dep],
  pic: true,
)

pybn_core_dep = declare_dependency(
  link_with: [bnlearn_lib, nmath_lib, linpack_lib],
  include_directories: compat_inc,
  dependencies: [lapack, blas, m_dep],
)
"""


def listing(pattern):
    return sorted(
        os.path.relpath(p, SRC_C).replace(os.sep, "/")
        for p in glob.glob(os.path.join(SRC_C, pattern), recursive=True)
    )


def block(name, files):
    body = "\n".join(f"  '{f}'," for f in files)
    return f"{name} = files(\n{body}\n)\n"


def main():
    bnlearn = listing("bnlearn/**/*.c")
    compat = listing("compat/*.c")
    rsupport = listing("rsupport/qsort.c")
    nmath = listing("nmath/*.c")
    linpack = listing("linpack/*.f")

    if not bnlearn or not nmath:
        sys.exit("vendored sources are missing; run tools/fetch_upstream.sh")

    out = os.path.join(SRC_C, "meson.build")
    with open(out, "w") as f:
        f.write(HEADER)
        f.write("\n")
        f.write(block("bnlearn_sources", bnlearn + compat + rsupport))
        f.write("\n")
        f.write(block("nmath_sources", nmath))
        f.write("\n")
        f.write(block("linpack_sources", linpack))
        f.write(FOOTER)

    print(f"wrote {out}: {len(bnlearn + compat + rsupport)} core, "
          f"{len(nmath)} nmath, {len(linpack)} fortran")


if __name__ == "__main__":
    main()
